apiVersion: v1
kind: Service
metadata:
  name: study-app-api
  namespace: study-app
  labels:
    app: study-app-api
spec:
  type: ClusterIP
  selector:
    app: study-app-api
  ports:
    - name: http
      port: 8000
      targetPort: http
