"""Centralized OpenAPI examples grouped by API domain."""

from app.openapi.examples.errors import (
    IDEMPOTENCY_KEY_CONFLICT_ERROR_EXAMPLE,
    IDEMPOTENCY_KEY_REQUIRED_ERROR_EXAMPLE,
    SECURITY_AUTH_REQUIRED_ERROR_EXAMPLE,
    SECURITY_BODY_TOO_LARGE_ERROR_EXAMPLE,
    SECURITY_RATE_LIMIT_EXCEEDED_ERROR_EXAMPLE,
    TIMEZONE_VALIDATION_ERROR_EXAMPLE,
    USER_CREATE_REQUIRED_FIELD_ERROR_EXAMPLE,
    USER_EXISTS_ERROR_EXAMPLE,
)
from app.openapi.examples.users import (
    FULL_NAME_EXAMPLES,
    INVALIDATION_REASON_UUID_EXAMPLES,
    IS_ROW_INVALID_EXAMPLES,
    SYSTEM_USER_ID_EXAMPLES,
    SYSTEM_UUID_EXAMPLES,
    TIMEZONE_EXAMPLES,
    USER_CREATE_REQUEST_EXAMPLES,
    USERNAME_EXAMPLES,
)

__all__ = [
    "FULL_NAME_EXAMPLES",
    "INVALIDATION_REASON_UUID_EXAMPLES",
    "IS_ROW_INVALID_EXAMPLES",
    "SYSTEM_USER_ID_EXAMPLES",
    "SYSTEM_UUID_EXAMPLES",
    "IDEMPOTENCY_KEY_CONFLICT_ERROR_EXAMPLE",
    "IDEMPOTENCY_KEY_REQUIRED_ERROR_EXAMPLE",
    "SECURITY_AUTH_REQUIRED_ERROR_EXAMPLE",
    "SECURITY_BODY_TOO_LARGE_ERROR_EXAMPLE",
    "SECURITY_RATE_LIMIT_EXCEEDED_ERROR_EXAMPLE",
    "USER_CREATE_REQUIRED_FIELD_ERROR_EXAMPLE",
    "TIMEZONE_EXAMPLES",
    "TIMEZONE_VALIDATION_ERROR_EXAMPLE",
    "USER_EXISTS_ERROR_EXAMPLE",
    "USERNAME_EXAMPLES",
    "USER_CREATE_REQUEST_EXAMPLES",
]
