"""Centralized OpenAPI examples grouped by API domain."""

from app.openapi.examples.users import (
    FULL_NAME_EXAMPLES,
    INVALIDATION_REASON_UUID_EXAMPLES,
    IS_ROW_INVALID_EXAMPLES,
    SYSTEM_USER_ID_EXAMPLES,
    SYSTEM_UUID_EXAMPLES,
    TIMEZONE_EXAMPLES,
    USERNAME_EXAMPLES,
    USER_REGISTER_REQUEST_EXAMPLES,
)
from app.openapi.examples.errors import (
    REGISTER_REQUIRED_FIELD_ERROR_EXAMPLE,
    TIMEZONE_VALIDATION_ERROR_EXAMPLE,
    USER_EXISTS_ERROR_EXAMPLE,
)

__all__ = [
    "FULL_NAME_EXAMPLES",
    "INVALIDATION_REASON_UUID_EXAMPLES",
    "IS_ROW_INVALID_EXAMPLES",
    "SYSTEM_USER_ID_EXAMPLES",
    "SYSTEM_UUID_EXAMPLES",
    "REGISTER_REQUIRED_FIELD_ERROR_EXAMPLE",
    "TIMEZONE_EXAMPLES",
    "TIMEZONE_VALIDATION_ERROR_EXAMPLE",
    "USER_EXISTS_ERROR_EXAMPLE",
    "USERNAME_EXAMPLES",
    "USER_REGISTER_REQUEST_EXAMPLES",
]

