"""Scan docs HTML and emit a combined JS bundle for the employee portal.

1. ``data-maintainer-ids`` on any page under ``docs/`` → pages maintained per person id.
2. Profile pages ``docs/internal/portal/people/*/index.html`` with ``data-person-*`` on ``<body>`` →
   people list for the portal index and editor avatars.

Output: ``docs/assets/docs-portal-data.js`` (``window.__DOCS_PORTAL_DATA__``).
Run via ``make docs-fix`` or: ``python scripts/collect_docs_portal_data.py``
"""

from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DOCS_ROOT = PROJECT_ROOT / "docs"
OUT_FILE = PROJECT_ROOT / "docs" / "assets" / "docs-portal-data.js"

MAINTAINER_ATTR_RE = re.compile(
    r"""data-maintainer-ids\s*=\s*["']([^"']*)["']""",
    re.IGNORECASE | re.DOTALL,
)
BODY_OPEN_RE = re.compile(r"<body\b([^>]*)>", re.IGNORECASE | re.DOTALL)
TITLE_RE = re.compile(r"<title[^>]*>([^<]*)</title>", re.IGNORECASE)


def _attr(attrs: str, name: str) -> str | None:
    m = re.search(rf'{re.escape(name)}\s*=\s*["\']([^"\']*)["\']', attrs, re.IGNORECASE | re.DOTALL)
    return m.group(1).strip() if m else None


def _page_title(html: str, rel_path: str) -> str:
    m = TITLE_RE.search(html)
    if m:
        return m.group(1).strip()
    return rel_path


def collect_maintainer_pages() -> dict[str, list[dict[str, str]]]:
    """Build person_id -> list of {path, title} from HTML under docs/."""
    by_person: dict[str, list[dict[str, str]]] = defaultdict(list)
    if not DOCS_ROOT.is_dir():
        return dict(by_person)

    for path in sorted(DOCS_ROOT.rglob("*.html")):
        rel = path.relative_to(DOCS_ROOT).as_posix()
        if rel.startswith("assets/"):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        m = MAINTAINER_ATTR_RE.search(text)
        if not m:
            continue
        raw = m.group(1).strip()
        if not raw:
            continue
        ids = [x.strip() for x in raw.split(",") if x.strip()]
        if not ids:
            continue
        title = _page_title(text, rel)
        entry = {"path": rel, "title": title}
        for pid in ids:
            by_person[pid].append(entry)

    for pid in by_person:
        by_person[pid].sort(key=lambda x: x["path"])
    return dict(by_person)


def collect_people_from_profiles() -> list[dict[str, str | list[str]]]:
    """Parse profile pages; body must declare data-person-id and related attributes."""
    people: list[dict[str, str | list[str]]] = []
    base = DOCS_ROOT / "internal" / "portal" / "people"
    if not base.is_dir():
        return people

    for index_html in sorted(base.glob("*/index.html")):
        slug_dir = index_html.parent.name
        try:
            text = index_html.read_text(encoding="utf-8")
        except OSError:
            continue
        m = BODY_OPEN_RE.search(text)
        if not m:
            continue
        attrs = m.group(1)
        person_id = _attr(attrs, "data-person-id")
        if not person_id:
            continue
        slug = _attr(attrs, "data-person-slug") or slug_dir
        display_name = _attr(attrs, "data-display-name")
        github = _attr(attrs, "data-github")
        photo_file = _attr(attrs, "data-photo") or "photo.jpg"
        groups_raw = _attr(attrs, "data-groups") or ""
        groups = [x for x in groups_raw.split() if x]
        if not display_name or not github:
            continue
        photo_from_docs = f"internal/portal/people/{slug}/{photo_file}"
        people.append(
            {
                "personId": person_id,
                "slug": slug,
                "github": github,
                "displayName": display_name,
                "photo": photo_from_docs,
                "groups": groups,
            }
        )

    people.sort(key=lambda p: str(p["displayName"]).lower())
    return people


def write_js(maintainer_pages: dict[str, list[dict[str, str]]], portal_people: list[dict]) -> None:
    """Write window.__DOCS_PORTAL_DATA__."""
    payload = {
        "maintainerPages": maintainer_pages,
        "people": portal_people,
    }
    dumped = json.dumps(payload, ensure_ascii=False, indent=2)
    body = (
        "/* Generated by scripts/collect_docs_portal_data.py — do not edit by hand. */\n"
        '"use strict";\n'
        f"window.__DOCS_PORTAL_DATA__ = {dumped};\n"
    )
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(body, encoding="utf-8")


def main() -> int:
    pages = collect_maintainer_pages()
    people = collect_people_from_profiles()
    write_js(pages, people)
    print(
        f"→ Wrote {OUT_FILE.relative_to(PROJECT_ROOT)} "
        f"({len(pages)} maintainer id(s), {len(people)} profile(s))",
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
