#!/usr/bin/env python3
"""Render ``k8s/configmap.yaml`` from ``k8s/app.env`` (non-secret pod configuration)."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml  # type: ignore[import-untyped]
from dotenv import dotenv_values

ROOT = Path(__file__).resolve().parents[1]
APP_ENV_PATH = ROOT / "k8s" / "app.env"
OUTPUT_PATH = ROOT / "k8s" / "configmap.yaml"

HEADER = (
    "# Generated by scripts/render_k8s_configmap.py — do not edit by hand.\n"
    "# Source of truth: k8s/app.env\n"
)


def load_data() -> dict[str, str]:
    """Load key/value pairs from ``k8s/app.env`` (dotenv syntax, skip blanks)."""
    raw = dotenv_values(APP_ENV_PATH)
    out: dict[str, str] = {}
    for k, v in raw.items():
        if k is None or v is None:
            continue
        key = k.strip()
        if not key or key.startswith("#"):
            continue
        out[key] = str(v).strip()
    return out


def build_manifest(data: dict[str, str]) -> dict[str, object]:
    """Build the ConfigMap object; ``data`` keys sorted for stable diffs."""
    return {
        "apiVersion": "v1",
        "kind": "ConfigMap",
        "metadata": {
            "name": "study-app-api-config",
            "namespace": "study-app",
        },
        "data": dict(sorted(data.items())),
    }


def render() -> str:
    data = load_data()
    if not data:
        print(f"error: no key-value pairs in {APP_ENV_PATH}", file=sys.stderr)
        raise SystemExit(1)
    manifest = build_manifest(data)
    body = yaml.dump(
        manifest,
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
    )
    return HEADER + "\n" + body


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if configmap.yaml would change (without writing).",
    )
    args = parser.parse_args()
    if not APP_ENV_PATH.is_file():
        print(f"error: missing {APP_ENV_PATH}", file=sys.stderr)
        raise SystemExit(1)
    rendered = render()
    if args.check:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.is_file() else ""
        if rendered != current:
            print(
                f"error: {OUTPUT_PATH} is out of sync with {APP_ENV_PATH}\n"
                "  Run: make k8s-render-configmap",
                file=sys.stderr,
            )
            raise SystemExit(1)
        return
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
